### ISSUE TITLE
Not obvious how to build assets.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-dashboard#118]
After creating a shared app, I'm presented with an error message that I need to "Build Assets"

However, there's no button to perform the command.

![buildassets](https://cloud.githubusercontent.com/assets/2374718/22157578/37a0e3bc-df06-11e6-8bc5-3fb76e9e22a9.png)

**Comment by nickjer** [comment]
That is because this validation:

https://github.com/OSC/ood-dashboard/blob/2f1c28a03a39d0d413a08399d81536778b535a3c/app/models/usr_product.rb#L2

is missing a conditional along the lines of:

https://github.com/OSC/ood-dashboard/blob/2f1c28a03a39d0d413a08399d81536778b535a3c/app/models/product.rb#L22

which was added at a later date.
