### ISSUE TITLE
Display MOTD even if unformatted

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-dashboard#150]
Would it be possible to display `/etc/motd` if it is unformatted. Similar to the way we did it in the past with just a `<pre></pre>` tag? This would then make the MOTD option available to most centers right away.

**Comment by ericfranz** [comment]
This feature needs a proposed design. Just attach it to this issue.

1. What environment variable for configuration will be used? MOTD_FORMAT probably makes sense to go along with MOTD_PATH?
2. Do we want to use the default <pre>. Bootstrap places that in a well, and it might look ugly to have a giant well in the center of the front page. We might want to customize styles in this case.
3. Since we will have multiple MOTD formatters, we will want to be able to use different formatters based on the specified format. This will let us easily add an RSS format in the future. So how will the code change to accommodate this?

**Comment by ericfranz** [comment]
For reference: https://github.com/OSC/ood-dashboard/wiki/Message-of-the-Day

**Comment by ericfranz** [comment]
Suggested formats:

* osc
* markdown
* plaintext
* rss

**Comment by brianmcmichael** [comment]
#151 has been merged
