### ISSUE TITLE
Separate enabling app sharing from enabling app development

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#212]
Use OOD_APP_DEVELOPMENT separate from OOD_APP_SHARING for app development dropdown to appear

**Comment by basilgohar** [comment]
@ericfranz I am a little concerned that this is simpler than I thought it would be – there are two references to OOD_APP_SHARING in the Dashboard codebase: ./config/routes.rb & ./app/apps/nav_config.rb.  Both have to do with showing the develop menu/options or allowing the routes in question.

What this leads me to believe is that swapping OOD_APP_DEVELOPMENT for OOD_APP_SHARING in both cases will resolve this issue for now in terms of Dashboard changes, and I think that is what we discussed in my office.  I'm just afraid I'm oversimplifying this since I am not so familiar with the dev workflow, not having used it myself.

**Comment by ericfranz** [comment]
This isn't just a setting name change. The OOD_APP_SHARING "feature flag" controls:

1. whether or not to show the Develop dropdown
2. display of the "Shared Apps (Production)" link in the dropdown
3. route to a view of all the "Shared Apps" to launch
4. changing the root of the dashboard to be this "Shared Apps" view (with the MOTD pushed to the right)
4. routes to access and manage "Shared Apps" and Sandbox apps

In other words, 

1. currently when OOD_APP_SHARING is enabled, you get this: https://apps.awesim.org/pun/sys/dashboard
2. when OOD_APP_SHARING is disabled, you get this: https://ondemand.osc.edu/pun/sys/dashboard

We want OOD_APP_DEVELOPMENT to enable:

1. display the Develop dropdown (of course this can be overridden with custom initializer like in AweSim)
2. enable route to Sandbox apps

We want OOD_APP_SHARING to enable:

1. enable the route for the user view of the shared apps, and change the root of the site to be this (long term we don't want this, but this maintains the status quo right now => merging the interface of AweSim and OnDemand into one interface would remove this requirement)
2. Add the link to Shared Apps (Production) in the develop dropdown (if it exists)
3. Enable the route to Shared Apps (Production) page for developers to share their own apps

**Comment by nickjer** [comment]
What about the case for `OOD_APP_DEVELOPMENT=false` and `OOD_APP_SHARING=true`?
