### ISSUE TITLE
Add "new product" option: "Copy app"

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#214]
"Copy app" will look nearly identical to "Clone app" but will call git remote remove origin after it is created. It will still accept a git remote.

Be sure to add a new route, view... Not sure about naming. We already have `new_from_git_remote`. Maybe `new_from_git_remote_copy`?

Worth asking if this is the right approach. Is it better to add "make this a copy" checkbox to the new_from_git_remote form instead? We would of course want to call out this form option if we did this. It would make the code simpler.

Then we would just have New Product go straight to new_from_git_remote until we added more options.

**Comment by nickjer** [comment]
> Is it better to add "make this a copy" checkbox to the new_from_git_remote form instead?

Since we are basically doing everything that "Clone App" offers but with some post-processing afterwards, I feel a checkbox called "Make a new Git Project from this." would be a simpler option.

Also, "Copy app" makes me think I can copy it from a URL or from a directory on the local file system. Which may be a nice future addition but not necessary right now.
