### ISSUE TITLE
When a iHPC job submission fails, provide debug link in error message

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#218]
For example, I'm in 2 projects and don't specify a one in the project field. I submit the job and I see an error. At the bottom of the error message, I should see the path to the corresponding job directory for debugging purposes, along with links to open the path in the file explorer or the shell app (or both?)

**Comment by nickjer** [comment]
The example you gave is currently not possible. If a job fails to be submitted to the resource manager then we delete the staging directory here:

https://github.com/OSC/ood-dashboard/blob/4f365a6ee720b8e07c638db6c58587c464f93d2d/app/models/batch_connect/session.rb#L153

This was to reduce the amount of clutter for invalid jobs.

Also if the session fails due to staging error, then it is also not possible because the staged directory won't have been staged:

https://github.com/OSC/ood-dashboard/blob/4f365a6ee720b8e07c638db6c58587c464f93d2d/app/models/batch_connect/session.rb#L138-L141

**Comment by nickjer** [comment]
So do you want to keep staged directories if jobs fail to be submitted?

**Comment by nickjer** [comment]
Update: I now keep staging directories that have failed job submissions.
