### ISSUE TITLE
Larger logos cause navbar to appear stretched

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-dashboard#222]
If a site uses a large logo, then the navbar will stretch:

![screenshot from 2017-08-11 14-41-22](https://user-images.githubusercontent.com/4260509/29227304-60249008-7ea3-11e7-829c-eeeb7f2c89b7.png)

**Comment by ericfranz** [comment]
What do you suggest for this? 

Either we remove the ability to use logos in the navbar, we **stop using the navbar**, or we put ALL of the navbar on a second line if the logo is a certain width.

I actually proposed stop using the navbar months ago but that was shot down because of time constraints.

FWIW I want to collapse Files Jobs and Clusters into a single menu called Cluster Access. But that risks to be too long if the site has 6 or 10 clusters... (one line for each shell app, and then files and jobs on top of that).

For the master branch, the header is absolutely positioned, so this is just visually unappealing, but the site is still usable.

**Comment by ericfranz** [comment]
> put ALL of the navbar on a second line if the logo is a certain width

This one could be difficult because we would be hacking on the bootstrap nav bar styles which unfortunately do not use flexbox.

**Comment by nickjer** [comment]
I am unsure of a solution at this time.

Note, this will affect OSC OnDemand if we ever enable the Develop dropdown.

**Comment by ericfranz** [comment]
No it won't as we do not put the logo in the header.

**Comment by nickjer** [comment]
Ah that is right. Hah this is what I get for developing an AweSim dashboard on OSC OnDemand.

**Comment by nickjer** [comment]
One solution is we have to work with our external partners when this is observed as the Utah OnDemand dashboard has a somewhat long logo there.

**Comment by ericfranz** [comment]
Right. We would have to recommend making a smaller logo and having a bigger logo on the main page.

For example, I could see at OSC, if we switched from the red navbar to the default light grey navbar like AweSim, but put an OSC Logo in top left, we could just put the logo and not have the text i.e.:

![screen 2017-08-11 at 3 04 11 pm](https://user-images.githubusercontent.com/512333/29228075-6179709c-7ea6-11e7-8856-c6f8b00c089f.png)

or that and OSC to the right...
