### ISSUE TITLE
Get rid of the "trash" feature and deleting an app

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#234]
Instead, deleting an app should show you a page with directions on how to delete it, and a link to the shell, i.e. open the shell to this directory, then type rm -rf app

**Comment by nickjer** [comment]
Due to the tricky nature of NFS, that may not actually delete an app that someone is currently running. As files that are currently open won't be deleted, but instead renamed to `.nfsXXXXXXXX`, and the directory continues to hang around (this led to confusion before). That is one of the reasons why we delete apps using the `mv` command.

I also like the Trash can feature as I have found myself restoring apps a couple of times in the past.

**Comment by nickjer** [comment]
Also the Shell App doesn't work for Safari users when using Basic Auth, so if we intend on going this route we may want to think about holding off until this is fixed for all sites. Otherwise app developers will be unable to delete apps anymore through the OOD portal.

**Comment by ericfranz** [comment]
The deletion directions could say to mv to a _random_number in the same directory or in tmp then delete. Or rm -rf && mv to a random directory in /tmp/

**Comment by laser505t** [comment]
Fixed with #394
