### ISSUE TITLE
Fix shell setup for LSF

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#262]
For LSF, set the login shell when submitting jobs:

https://github.com/OSC/ood-dashboard/blob/a65d101b1e339d3644a764935dedf301faf9be77/app/models/batch_connect/session.rb#L230-L239

When doing this, the adapter itself should set -env "all" if using LSF 9+. Also, we should verify that LSF 9+, when using -L "/bin/bash" and -env "all" at the same time that environment variables get passed through.

Another alternative would be to not have these adapter specific options in https://github.com/OSC/ood-dashboard/blob/a65d101b1e339d3644a764935dedf301faf9be77/app/models/batch_connect/session.rb#L230-L239 and instead have a "set login shell" option on the OodCore::Job::Script object. Slurm could ignore it, claiming "it sets the shell from shebang of the script". But LSF and Torque and PBS Pro adapters could add arguments appropriately. This might be the best...

**Comment by nickjer** [comment]
I think for now we should just add:

```ruby
when "lsf"
  opts[:native] = ["-L", "/bin/bash"] + opts.fetch(:native, [])
end
```

since we can confirm this works. I don't think we should add any LSF 9+ specific chunk of code unless we can confirm that it works and we don't end up breaking something (also I don't think the LSF adapter currently supports querying the version, or do we use an lsf9 adapter similar to sqlite3?). It is easier to add a command line argument from the Interactive App's `submit.yml.erb` file if worse comes to worst than it is to remove one set from within the Dashboard.

Also, I am for adding this to the `ood_core` library, but I feel we need a firmer grasp on this before making it a guaranteed resource-manager agnostic interface option that all apps can use with confidence. With it being in the Dashboard right now, it is easier for it to evolve with less consequences and quicker turn-around. I think there was a previous discussion we had on a similar topic, I don't remember where off the top of my head, but this is getting off topic.
