### ISSUE TITLE
Logout fails for AweSim dashboard

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-dashboard#31]
When I go to logout it sends me to the OpenID Connect logout and not Shibboleth:

![image](https://cloud.githubusercontent.com/assets/4260509/19392488/f1a5be72-91fe-11e6-878d-1db36d995afd.png)

**Comment by nickjer** [comment]
Some updated info:

Visiting this link will log you out of awesim.org

```
https://apps-dev.awesim.org/Shibboleth.sso/Logout
```

but you will be automatically logged back in.

Visiting this link will log you out of the IdP:

```
https://idp.osc.edu/idp/profile/Logout
```

**Comment by nickjer** [comment]
A dirty fix is this...

```
https://apps-dev.awesim.org/Shibboleth.sso/Logout?return=https://idp.osc.edu/idp/profile/Logout
```

**Comment by ericfranz** [comment]
Then the user sees:

>This page is displayed when a logout operation at the Identity Provider completes. This page is an example and should be customized. It is not fully internationalized because the presentation will be a highly localized decision, and we don't have a good suggestion for a default.

![screen shot 2016-10-14 at 2 59 05 pm](https://cloud.githubusercontent.com/assets/512333/19399285/cc2e748e-921e-11e6-852a-73d8feda4520.png)

**Comment by nickjer** [comment]
Yep, but at least they can logout.

I didn't say it was pretty.

**Comment by ericfranz** [comment]
I thought the solution would be to make a template string. Something simple like:

```ruby
  def set_logout_url
    if ENV['OOD_DASHBOARD_LOGOUT_URL'].present?
      @logout_url = (ENV['OOD_DASHBOARD_LOGOUT_URL'] % { login: ERB::Util.u(request.base_url) })
    else
      @logout_url = nil
    end
  end
```

And then we could set in ENV vars:

```
OOD_DASHBOARD_LOGOUT_URL='/oidc?logout=%{login}'
OOD_DASHBOARD_LOGOUT_URL="https://apps-dev.awesim.org/Shibboleth.sso/Logout?return=https://idp.osc.edu/idp/profile/Logout"
```

This actually works. But its shortsighted. It's not like I could just eventually do:

```
OOD_DASHBOARD_LOGOUT_URL='https://apps-dev.awesim.org/Shibboleth.sso/Logout?return=https://idp.osc.edu/idp/profile/Logout?redirect_url=%{login}'
```

when the `https://idp.osc.edu/idp/profile/Logout` supports a redirect, because this logout will .

In the past, our solution to this type of problem was to make `https://idp.osc.edu/idp/profile/Logout` smart - based on a query param or knowing where it came from, it would handle redirecting to AweSim or OnDemand end points appropriately.

This is an example of the type of thing that would be easier to configure if we provided the ability to set all of these configuration options using a Rails initializer instead of dotenv files.

**Comment by nickjer** [comment]
This is probably something that needs to be owned by the Apache config. Since the Apache config knows the authentication module chosen.

That way, you'd just send the user to `/logout`, and Apache would redirect the user to the appropriate place.

**Comment by ericfranz** [comment]
https://github.com/OSC/ood-dashboard/pull/33
