### ISSUE TITLE
Add custom shortcuts in the Files menu

### ISSUE THREAD

**Issue by kcgthb** [OSC/ood-dashboard#362]
Hi!

I'm trying to  add some custom shortcuts to specific directories in the drop-down list under the Files menu, but I can't really figure out how to do this from the documentation.

Could you please advise?

Thanks!

**Comment by kcgthb** [comment]
As a bonus question, is it possible to get those paths from environment variables defined in the user's profile?

**Comment by ericfranz** [comment]
Try https://osc.github.io/ood-documentation/master/applications/dashboard.html#add-shortcuts-to-files-menu. Note we need to fix this documentation for the new release! The config has all moved to /etc, so for the dashboard this initializer would go under /etc/ood/config/apps/dashboard/initializers/ and and an example is here: https://github.com/OSC/osc-ood-config/blob/master/ondemand.osc.edu/apps/dashboard/initializers/ood.rb

This approach does resolve the path at application start time instead of per request but there are clever workarounds for that. It’s Ruby code running as the user so you can do whatever you want to build these paths. Note that the PUN process is started using sudo so that does wipe the environment so it’s possible certain env variables that you want to use will not be set. I believe there are also configuration options for nginx_stage to work around that if necessary so let us know if you run into problems.

Finally since this approach builds an array of file shortcuts during the Rails app initialization to see modifications to the config you will need to restart your PUN (Help - Restart Web Server”) or force restart the individual dashboard app by touching the tmp/restart.txt file under the app’s directory.

**Comment by kcgthb** [comment]
Ooh, great, I somehow missed that part in the docs, thanks for pointing it out!

I managed to add custom links to the Files menu, but not using user-level environment variables: we define those environment variables in a `/etc/profile.d/` script, and it appears that the sudo command that starts the PUN process indeed skips that part. 

If you could point me to `nginx_stage` options that would allow the PUN process to inherit the user's complete environment, that'd be much appreciated.

Thanks!

**Comment by nickjer** [comment]
Currently there is no option in `nginx_stage` to re-enable a user's shell environment as I purposely disabled it here:

https://github.com/OSC/nginx_stage/blob/439119638c95ba8deda658953330ac4c6382b1df/templates/pun.conf.erb#L26

That is because a user's shell environment is a mine field that causes many things to break in the oddest of places. So we currently run all the OnDemand apps in a more sterile and testable environment.

If you still want to launch apps under a user's shell environment and believe a user won't override necessary libraries or paths, there is a hacky way without needing to modify OnDemand's code directly (which can break things after updates).

You can modify the following options in the `/etc/ood/config/nginx_stage.yml` file as such:

```yaml
# /etc/ood/config/nginx_stage.yml
---
passenger_ruby: '/my/custom/bin/ruby'
passenger_nodejs: '/my/custom/bin/node'
passenger_python: '/my/custom/bin/python'
```

Where these files are your custom wrappers around our wrappers (exactly like Inception). So an example of one of these wrappers will look like (for `/my/custom/bin/ruby`):

```shell
#!/bin/bash -l

exec /opt/ood/nginx_stage/bin/ruby "${@}"
```

Note that the shebang `#!/bin/bash -l` is set to load a *login* shell. This will load the user's environment before exec'ing off the Ruby code that launches the Ruby app.

After making the above changes I believe you will need to only restart your PUN to see the changes take effect. But usually you should run:

```console
$ sudo /opt/ood/nginx_stage/sbin/update_nginx_stage
```

everytime you make changes to `/etc/ood/config/nginx_stage.yml`.

**Comment by kcgthb** [comment]
I see, thank you so much for the  very complete explanation. This makes complete sense, and that perfectly answers my question.

Thanks!

**Comment by ericfranz** [comment]
This is another great example of how we are either missing documentation or documentation is not easily found. Fixing that problem is part of https://github.com/OSC/Open-OnDemand/issues/27. I'll close this issue now that https://github.com/OSC/Open-OnDemand/issues/27 has a reference to this.
