### ISSUE TITLE
Errors in PUN log: No passenger_native_support.so found for current Ruby interpreter.

### ISSUE THREAD

**Issue by kcgthb** [OSC/ood-dashboard#363]
Hi,

I'm getting this error in the PUN logs:
```
==> /var/log/nginx/kilian/error.log <==
App 15059 stdout:
App 15059 stderr:  --> No passenger_native_support.so found for current Ruby interpreter.
App 15059 stderr:      This library provides various optimized routines that make
App 15059 stderr:      Phusion Passenger faster. Please run 'sudo yum install passenger-devel-4.0.50'
App 15059 stderr:      so that Phusion Passenger can compile one on the next run.
App 15059 stderr:  --> Continuing without passenger_native_support.so.
App 15059 stderr: Rails Error: Unable to access log file. Please ensure that /var/www/ood/apps/sys/dashboard/log/production.log exists and is writable (ie, make it writable for user and group: chmod 0664 /var/www/ood/apps/sys/dashboard/log/production.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
App 15059 stdout:
App 15059 stdout: [2018-04-27 16:49:23 -0700 ]  INFO "method=GET path=/pun/sys/dashboard/ format=html controller=DashboardController action=index status=200 duration=45.16 view=40.10"
```

which prompts two questions:
1. what should I do about the `passenger_native_support.so` message? I have the `rh-passenger40-scldevel-2.0-8.el7.x86_64` RPM installed, but that doesn't seem to make any difference

2. Is the per-user NGINX process supposed to log things in a global log file such as `/var/www/ood/apps/sys/dashboard/log/production.log`?

**Comment by nickjer** [comment]
I can understand the confusion, but the good news is that these messages can be ignored.

The first message about `passenger_native_support.so` is because we use the SCL package `rh-passenger` which doesn't come with the native support for Ruby 2.2. So it will just fallback to using pure Ruby.

The second message `Unable to access log file` is because of standard Rails behavior. By default Rails will create a log file and stream the log to it. Instead we actually stream the log to `STDOUT` instead of a log file. But Rails still *attempts* to create the log file even if it doesn't actually use it. Due to the per-user nature of OnDemand, Rails won't have write permissions to this directory so it complains but carries on its merry way.

These warning messages do not affect OnDemand's function and/or behavior. They unfortunately have been too low priority for our team to explore how to disable them. If someone else wants to take a stab at disabling these messages it would be appreciated:

- https://github.com/OSC/nginx_stage/issues/39
- https://github.com/OSC/ood-dashboard/issues/364
- https://github.com/OSC/ood-activejobs/issues/158
- https://github.com/OSC/ood-myjobs/issues/262
- https://github.com/OSC/ood-fileeditor/issues/70

**Comment by kcgthb** [comment]
Thanks for the clarification!
