### ISSUE TITLE
Consider Removing OSCConnect From BC Native Instructions

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/ood-dashboard#382]
Do we still want / need to support OSCConnect given that Windows users can easily connect visually through the browser?

**Comment by ericfranz** [comment]
I thought there were some users still using OSCConnect, though I'm not sure if that is the case.

Benefit of OSCConnect is the native TurboVNC client. It has copy/paste support and is more performant than noVNC. Though we haven't had any complaints from users using noVNC.

**Comment by ericfranz** [comment]
>Eric:  Are we actively maintaining OSC Connect?  Do we intend to continue to maintain it?  Can we somehow check the logs to see if there is active usage of it to connect to the systems?

- EMC2 uses OSC Connect because that is how VFT currently works.
- Thijs Heus from Cleveland State U and his team uses OSC Connect. See INC0333743. 
- May be others. Need to do investigate what kind of logs are present. One thing that is present is https://github.com/OSC/osc-connect/graphs/traffic. It shows https://github.com/OSC/osc-connect/releases/tag/0.97.6689.16821 as being accessed by 23 unique visitors. Since osc-connect updates itself by checking the releases from the GitHub page, this is an indication of how many users were using osc-connect when the last release was created (Apr 25 of this year) which I did so that Brian could show me the process.

**Comment by ericfranz** [comment]
Actually that traffic page is not what really matters. It is the https://api.github.com/repos/osc/osc-connect/releases/10718204

```
$ curl -s https://api.github.com/repos/osc/osc-connect/releases/10718204 | jq '.assets' | egrep 'name|download_count'
    "name": "AweSimConnect.exe",
    "download_count": 19,
    "name": "OSCConnect.exe",
    "download_count": 91,

**Comment by ericfranz** [comment]
From Thijs Heus in INC0333743:

>The usecase of connecting through OSCConnect/VNC over the noVNC web connection is that it is easier to run the latter full screen, with short cuts and copy/paste working.

**Comment by MorganRodgers** [comment]
Sounds like there are enough people who still value OSCConnect that we should keep it. Closing this.
