### ISSUE TITLE
Immediately after creating a sandbox app from existing repo, when I try to launch the app I get a  "bundle install error"

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-dashboard#39]
The lint errors in the details page actually checks to see that the gems all exist i.e. `bundle check`.

Minimally, however, we should probably show some lint errors on the index page that are really fast. One is simply the existence of a `vendor/bundle` directory.

![screen shot 2016-10-17 at 3 29 04 pm](https://cloud.githubusercontent.com/assets/512333/19457078/a4109d94-9492-11e6-9719-63ce2bb7e27c.png)

**Comment by nickjer** [comment]
I debated putting "some" errors on the index page. It suffers from a few problems:

1. The presentation will become very cluttered with the limited space. Especially if the developer has non-rails apps.

2. Developers may think the index page displays all possible errors if he/she sees a list of errors for an app. After satisfying all the errors they will be confused why the app still fails. Then we will need to direct them to the "Details" page for the full list of errors.

I leaned towards displaying the errors on the Details page because that is the first page they see after creating an app. That is also where they have the most control over the app.

**Comment by nickjer** [comment]
Another option is removing the ability to Launch an app from the index page. Force them to have to go through the Details page. This may be more beneficial to the developer.

Clearly this won't affect clients as they can still launch apps directly from the "Apps" index page.

**Comment by nickjer** [comment]
@ericfranz is this still an issue? Immediately after creating an app from a repo I am now taken to the Details view where I see all the lint errors.

**Comment by ericfranz** [comment]
No longer relevant.
